- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - openstack-lower-constraints-jobs
      - build-openstack-docs-pti
      - docs-on-readthedocs
    check:
      jobs:
        - build-openstack-releasenotes
    gate:
      jobs:
        - build-openstack-releasenotes
    vars:
        rtd_webhook_id: '53170'
