#############################################################################
# Variables in header                                                       #
#############################################################################

#############################################################################
# Variables in path                                                         #
#############################################################################

session_id:
  description: |
    Session ID
  in: path
  required: false
  type: string
  min_version: \> 1

uuid-path:
  description: |
    uuid
  in: path
  required: true
  type: string

#############################################################################
# Variables in query                                                        #
#############################################################################

#############################################################################
# Variables in body                                                         #
#############################################################################
action-metadata:
  description: |
    Metadata; hints to plug-ins
  in: body
  required: true
  type: dictionary

action-plugin-name:
  description: |
    plug-in name. Default workflow executes same type of plug-ins in an
    alphabetical order
  in: body
  required: true
  type: string

action-plugin-type:
  description: |
    Type of the action plug-in. Default workflow supports:

      * pre: executed before the host specific plug-ins
      * post: executed after the host specific plug-ins
      * host: executed for every host
      * compute: executed for every compute host
      * controller: executed for every controller host

  in: body
  required: true
  type: integer

action-plugins:
  description: |
    List of action plug-ins.
  in: body
  required: true
  type: list of dictionaries

hosts:
  description: |
    Hosts to be maintained. An empty list can indicate hosts are to be
    discovered.
  in: body
  required: true
  type: list of strings

instance-actions:
  description: |
    instance ID : action string
  in: body
  required: true
  type: dictionary

instance-ids:
  description: |
    List of instance IDs.
  in: body
  required: true
  type: list of strings

maintenance-workflow-start-time:
  description: |
    Maintenance workflow start time.
  in: body
  required: true
  type: string

metadata:
  description: |
    Metadata; like hints to projects
  in: body
  required: true
  type: dictionary

upgrade-list:
  description: |
    List of needed SW upgrades
  in: body
  required: false
  type: list of dictionaries
  min_version: \> 1

uuid:
  description: |
    uuid
  in: body
  required: true
  type: string

uuid-list:
  description: |
    list of UUID strings
  in: body
  required: true
  type: string

workflow-name:
  description: |
    Maintenance workflow to be used.
  in: body
  required: true
  type: string

workflow-state:
  description: |
    Maintenance workflow state.
  in: body
  required: true
  type: string

workflow-state-reply:
  description: |
    There can have different values depending on what is the maintenance
    session state to reply to. In the below example, the maintenance state is
    'PLANNED_MAINTENANCE' and the reply state is formed by adding 'ACK\_' or
    'NACK\_' as the prefix to reply value.
  in: body
  required: true
  type: string
